"""Init

Revision ID: c60887af4498
Revises: 9aa465e51840
Create Date: 2023-12-15 04:34:21.032428

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c60887af4498"
down_revision: Union[str, None] = "9aa465e51840"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("is_archived", sa.Boolean(), nullable=False))
    op.drop_column("chat", "if_archived")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat",
        sa.Column("if_archived", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("chat", "is_archived")
    # ### end Alembic commands ###
