"""Update complaints

Revision ID: ed4cbb2aa444
Revises: 5ca05a12655b
Create Date: 2023-12-14 18:32:37.321983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed4cbb2aa444'
down_revision: Union[str, None] = '5ca05a12655b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint', 'photo_scan',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('complaint', 'photo_scan',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
